### PR TITLE
Fix for dev stringr

### PR DESCRIPTION
**Pull request by hadley**
str_detect() now errors if you give it an empty string, so we need to move the check one line up.

### CODE REVIEW

**Comment by msperlin** [comment]
Thanks @hadley. There are some errors in the CHECKS for ubuntu, but due to package XML. 

I'm still surprised with your PR. Are you doing this for all revdeps?

**Comment by hadley** [comment]
Yes, it's now our policy to fix revdeps that break due to breaking changes in tidyverse packages.

**Comment by msperlin** [comment]
Thanks again, appreciate it.

**Comment by hadley** [comment]
FYI stringr is now scheduled for release to CRAN on Dec 2.

**Pull request merged**
